name: "Install Emscripten Package"
description: "Install Emscripten package"
author: "Scott Doxey @neogeek"
branding:
  color: blue
  icon: upload-cloud

inputs:
  EMSDK_VERSION:
    description: "Emscripten SDK Version"
    required: false
    default: "4.0.18"
  CACHE_EMSCRIPTEN:
    description: "If the action should cache the Emscripten files."
    required: false
    default: "true"

runs:
  using: composite
  steps:
    - if: ${{ inputs.EMSDK_VERSION != '' }}
      name: Restore Emscripten Cache
      uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      id: cache-emscripten
      with:
        path: ./emsdk
        key: ${{ runner.os }}-emsdk-${{ inputs.EMSDK_VERSION }}

    - if: ${{ inputs.EMSDK_VERSION != '' && steps.cache-emscripten.outputs.cache-hit != 'true' }}
      name: Install Emscripten
      shell: bash
      run: |
        git clone https://github.com/emscripten-core/emsdk.git
        cd ./emsdk
        ./emsdk install ${{ inputs.EMSDK_VERSION }}

    - if: ${{ inputs.EMSDK_VERSION != '' && inputs.CACHE_EMSCRIPTEN != 'false' && steps.cache-emscripten.outputs.cache-hit != 'true' }}
      name: Store Emscripten Cache
      uses: actions/cache/save@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      with:
        path: ./emsdk
        key: ${{ runner.os }}-emsdk-${{ inputs.EMSDK_VERSION }}

    - name: Activate Emscripten
      shell: bash
      run: |
        cd ./emsdk
        ./emsdk activate ${{ inputs.EMSDK_VERSION }}

    - name: Setup Emscripten Environment
      shell: bash
      run: |
        cd ./emsdk
        chmod +x emsdk_env.sh
        source ./emsdk_env.sh
        echo "${EMSDK}" >> $GITHUB_PATH
        echo "${EMSDK}/upstream/emscripten" >> $GITHUB_PATH
        echo "${EMSDK}/node/${EMSDK_NODE##*/}/bin" >> $GITHUB_PATH
